Repository ISPP-23-24-Grupo-3/musclemate-frontend, pull requests merged in 2024-04, with the labels that each got.

#130 Feature/104 tickets equipment details client
  dev-dist/sw.js
  src/views/Equipment/EquipmentDetailsClient.jsx
Labels: enhancement, funcionalidad

#137 feat: gym details #136
  dev-dist/sw.js
  src/main.jsx
  src/views/Gyms/GymDetails.jsx
  src/views/Gyms/MyGymsOwner.jsx
Labels: enhancement, funcionalidad

#141 feat: Arreglar registro #134
  dev-dist/sw.js
  package-lock.json
  src/views/RegisterPage/RegisterClient.jsx
Labels: bug, enhancement, feedback

#142 Feature/138 deletes equipments gyms
  src/views/Equipment/EquipmentDetails.jsx
  src/views/Equipment/EquipmentDetailsClient.jsx
  src/views/Equipment/EquipmentList.jsx
  src/views/Equipment/EquipmentListClient.jsx
  src/views/Gyms/GymDetails.jsx
Labels: enhancement, funcionalidad

#162 Feature/144 restricciones por plan
  dev-dist/sw.js
  src/main.jsx
  src/utils/context/SubscriptionContext.jsx
  src/views/ClientHomePage/ClientHomePage.jsx
  src/views/Equipment/EquipmentDetailsClient.jsx
  src/views/EventsClasses/EventList.jsx
  src/views/EventsClasses/EventListClient.jsx
  src/views/Routines/Routines.jsx
  src/views/SubscriptionsPage/SubscriptionsPage.jsx
  src/views/Tickets/AddTickets.jsx
Labels: interfaz, funcionalidad

#171 Feature/163 registros feedback
  src/views/RegisterPage/RegisterClient.jsx
  src/views/RegisterPage/RegisterUser.jsx
Labels: bug

#166 Feature/147 perfil feedback
  src/components/Header/Header.jsx
  src/main.jsx
  src/views/ProfileOwner/ProfileOwner.jsx
  src/views/UserListing/ProfileClient.jsx
Labels: bug, enhancement, feedback, funcionalidad

#178 feat: equipment list feedback #164
  src/views/Equipment/EquipmentDetails.jsx
  src/views/Equipment/EquipmentList.jsx
Labels: bug, enhancement, feedback, funcionalidad

#176 Bugfix/155 feedback sprint 2 rutinas
  src/views/Routines/EditRoutine.jsx
  src/views/Routines/Routines.jsx
Labels: enhancement

#180 feat: feedback de serie
  package-lock.json
  package.json
  src/components/Routines/RoutineList.jsx
  src/components/Series/Series.jsx
  src/main.jsx
  src/views/Series/Series.jsx
  src/views/Workouts/EditWorkout.jsx
Labels: enhancement

#200 Feature/186 sugerencias piloto de workout
  src/components/Series/Series.jsx
  src/views/Routines/EditRoutine.jsx
  src/views/Workouts/EditWorkout.jsx
Labels: enhancement

#214 195 feedback sprint 3 s9 series
  src/components/Equipments.jsx
  src/components/Header/Header.jsx
  src/components/Series/Series.jsx
  src/main.jsx
  src/views/ClientHomePage/ClientHomePage.jsx
  src/views/Routines/Routines.jsx
  src/views/Statistics/StatisticsClient.jsx
  src/views/Workouts/EditWorkout.jsx
Labels: enhancement

#217 Feature/192 feedback gym
  src/views/Gyms/CreateGym.jsx
Labels: bug, feedback

#218 Feature/190 feedback listado maquinas
  src/views/Equipment/EquipmentDetails.jsx
  src/views/Equipment/EquipmentDetailsClient.jsx
  src/views/Equipment/EquipmentForm.jsx
  src/views/Equipment/EquipmentListClient.jsx
Labels: bug, enhancement, feedback

#220 fix: problemas en el register de client y user
  src/components/Gyms.jsx
  src/components/RHFSelect.jsx
  src/views/RegisterPage/RegisterClient.jsx
  src/views/RegisterPage/RegisterUser.jsx
Labels: bug

#221 feat: arreglar listado de maquinas cliente #198
  src/views/Equipment/EquipmentListClient.jsx
Labels: bug

#227 fix: arreglado visualizacion de nombres de maquinas
  src/views/Workouts/EditWorkout.jsx
Labels: bug
