Repository ISPP-23-24-Grupo-3/musclemate-frontend, pull requests merged in 2024-03, with the labels that each got.

#60 fix: momentary bad loading state on Authcontext
  dev-dist/sw.js
  src/utils/context/AuthContext.jsx
Labels: bug

#78 Feature/42 envio tickets usuario
  dev-dist/sw.js
  src/main.jsx
  src/views/Tickets/AddTickets.jsx
Labels: funcionalidad

#80 Feature/79 fix login
  dev-dist/sw.js
  src/components/Header/Header.jsx
  src/utils/context/AuthContext.jsx
  src/views/LoginPage/Login.jsx
Labels: feedback

#81 Mejorar la navegabilidad, página de inicio de cliente y mejora en diseño móvil
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header/Header.jsx
  src/main.jsx
  src/utils/context/AuthContext.jsx
  src/utils/functions/api.js
  src/views/ClientHomePage/ClientHomePage.jsx
  src/views/Equipment/EquipmentDetails.jsx
  src/views/Equipment/EquipmentList.jsx
  src/views/LoginPage/Login.jsx
  src/views/MainLayout/MainLayout.jsx
  src/views/OwnerHomePage/OwnerHomePage.jsx
  src/views/RegisterPage/RegisterClient.jsx
  src/views/RegisterPage/RegisterUser.jsx
  src/views/Routines/Routines.jsx
  src/views/TicketManagement/TicketManagement.jsx
  src/views/UserListing/Profile.jsx
  src/views/UserListing/Users.jsx
Labels: bug

#74 fix: search button changed due to feedback
  src/views/UserListing/Users.jsx
Labels: funcionalidad

#82 Feature/23 listado gym owner
  dev-dist/sw.js
  src/components/Header/Header.jsx
  src/main.jsx
  src/views/Gyms/MyGymsOwner.jsx
  src/views/OwnerHomePage/OwnerHomePage.jsx
Labels: funcionalidad

#91 feat: arreglar fallos equipment details #90
  dev-dist/sw.js
  src/views/Equipment/EquipmentDetails.jsx
Labels: feedback

#93 feat: arreglar tickets por fecha y estructura #92
  dev-dist/sw.js
  src/views/Equipment/EquipmentDetails.jsx
  src/views/TicketManagement/TicketManagement.jsx
Labels: feedback

#96 Feature/95 arreglos ticket
  dev-dist/sw.js
  src/views/Equipment/EquipmentDetails.jsx
  src/views/TicketManagement/TicketManagement.jsx
  src/views/Tickets/AddTickets.jsx
Labels: bug, feedback

#101 Feature/94 edit perfil cliente
  dev-dist/sw.js
  src/views/UserListing/Profile.jsx
Labels: enhancement, funcionalidad

#115 feat: añadido filtro por gimnasios en los equipments
  src/views/Equipment/EquipmentList.jsx
Labels: funcionalidad

#123 fix: subs feat integrated with backend
  src/views/SubscriptionsPage/SubscriptionsPage.jsx
  src/views/SuccessPage.jsx
Labels: bug

#129 Feature/102 create gym
  src/main.jsx
  src/views/Gyms/CreateGym.jsx
  src/views/Gyms/MyGymsOwner.jsx
Labels: enhancement, funcionalidad
