Repository ISPP-23-24-Grupo-3/musclemate-frontend, pull requests merged in 2024-05, with the labels that each got.

#254 Sugerencias Pilotos #241
  src/views/RegisterPage/RegisterClient.jsx
  src/views/RegisterPage/RegisterUser.jsx
  src/views/UserListing/Profile.jsx
  src/views/UserListing/ProfileClient.jsx
Labels: bug, enhancement, feedback

#255 Develop
  dev-dist/sw.js
  package-lock.json
  package.json
  src/assets/machines-icon.svg
  src/components/Equipments.jsx
  src/components/Header/Header.jsx
  src/components/Images.jsx
  src/components/MachineIcon.jsx
  src/components/PricingCard/PricingCard.jsx
  src/components/Series/Series.jsx
  src/components/Ticket/Ticket.jsx
  src/main.jsx
  src/utils/context/AuthContext.jsx
  src/utils/functions/api.js
  src/utils/functions/images.js
  src/utils/functions/stripe.js
  src/views/ClientHomePage/ClientHomePage.jsx
  src/views/Equipment/EquipmentDetails.jsx
  src/views/Equipment/EquipmentDetailsClient.jsx
  src/views/Equipment/EquipmentForm.jsx
  src/views/Equipment/EquipmentList.jsx
  src/views/Equipment/EquipmentListClient.jsx
  src/views/EventsClasses/EventList.jsx
  src/views/EventsClasses/EventListClient.jsx
  src/views/GymHomePage/GymHomePage.jsx
  src/views/Gyms/GymDetails.jsx
  src/views/OwnerHomePage/OwnerHomePage.jsx
  src/views/PricingPage/PricingPage.jsx
  src/views/ProfileOwner/ProfileOwner.jsx
  src/views/RegisterPage/RegisterClient.jsx
  src/views/RegisterPage/RegisterUser.jsx
  src/views/Routines/EditRoutine.jsx
  src/views/Statistics/StatisticsClient.jsx
  src/views/SubscriptionsPage/SubscriptionsPage.jsx
  src/views/SuccessPage.jsx
  src/views/TicketManagement/TicektManagementUser.jsx
  src/views/TicketManagement/TicketDetail.jsx
  src/views/TicketManagement/TicketManagement.jsx
  src/views/Tickets/AddTicketFromDetails.jsx
  src/views/Tickets/AddTickets.jsx
  src/views/UserListing/Profile.jsx
  src/views/UserListing/ProfileClient.jsx
  src/views/UserListing/Users.jsx
Labels: enhancement

#279 Feature/258 editar perfil cliente
  src/views/UserListing/ProfileClient.jsx
Labels: enhancement, feedback, funcionalidad
